Repository nebari-dev/jupyterlab-gallery, pull requests merged in 2024-06, with the labels that each got.

#10 Implement support for private repositories
  README.md
  jupyterlab_gallery/git_askpass.py
  jupyterlab_gallery/git_utils.py
  jupyterlab_gallery/gitpuller.py
  jupyterlab_gallery/handlers.py
  jupyterlab_gallery/manager.py
Labels: enhancement

#14 Fix stream breaking up, fix blocking of JupyterLab load on repository fetch
  jupyterlab_gallery/git_utils.py
  jupyterlab_gallery/gitpuller.py
  jupyterlab_gallery/manager.py
  src/gallery.tsx
  src/handler.ts
  src/types.ts
  style/base.css
Labels: bug

#19 Fix defaults for optionals, remove placeholder exhibits, do not add section if empty
  jupyterlab_gallery/handlers.py
  jupyterlab_gallery/manager.py
  src/index.ts
  src/types.ts
Labels: bug

#24 Add example entries for testing on binder
  binder/jupyter_gallery_config.json
  binder/start
Labels: maintenance

#27 Investigate the `xsrf` token issue
  jupyterlab_gallery/handlers.py
  jupyterlab_gallery/tests/test_handlers.py
  src/gallery.tsx
  src/handler.ts
Labels: bug

#20 Hide gallery without exhibits
  jupyterlab_gallery/handlers.py
  jupyterlab_gallery/manager.py
  src/index.ts
  src/types.ts
Labels: area: user experience 👩🏻‍💻, needs: review 👀, enhancement

#22 Improve tile display (buttons on hover, regular size)
  src/gallery.tsx
  style/base.css
Labels: enhancement
